### ISSUE TITLE
Rewrite the paper for IPDPS (Workflow Mini-Apps)

### ISSUE THREAD

**Issue by okilic1** [radical-cybertools/workflow-mini-apps#16]

**Comment by okilic1** [comment]
https://docs.google.com/document/d/1fnT2ZCgEmJpqXRp1EDLwz5M6W4RZOitk-kDKVfTr7tY/edit

**Comment by shantenujha** [comment]
Is this link in error? I don’t see the connection to mini-apps, sorry.

On Sep 25, 2023, at 6:13 PM, OZGUR OZAN KILIC ***@***.***> wrote:



https://docs.google.com/document/d/1fnT2ZCgEmJpqXRp1EDLwz5M6W4RZOitk-kDKVfTr7tY/edit

**Comment by okilic1** [comment]
Yes, there was a mistake; this link was supposed be in an other ticket

**Comment by andre-merzky** [comment]
Wohoo!
